spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:9005/
          predicates:
            - Path=/costumers/**
        - id: r2
          uri: http://localhost:9006/
          predicates:
            - Path=/products/**
